version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bollard
    versions:
    - 0.10.0
    - 0.9.0
    - 0.9.1
  - dependency-name: ctrlc
    versions:
    - 3.1.8
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: tokio
    versions:
    - 0.2.25
  - dependency-name: log
    versions:
    - 0.4.14
  - dependency-name: flexi_logger
    versions:
    - 0.17.1
  - dependency-name: snafu
    versions:
    - 0.6.10
  - dependency-name: structopt
    versions:
    - 0.3.21
