[package]
name = "container-per-ip"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.4.0-alpha.1"
tokio = "0.2.0-alpha.6"
tokio-timer = "0.3.0-alpha.5"
structopt = "0.3.4"
snafu = "0.6.0"
log = "0.4.8"
futures = "0.3.1"
lazy_static = "1.4.0"
multi-map = "1.2.0"
flexi_logger = "0.14.5"
ctrlc = "3.1.3"
