# syntax = denzp/cargo-wharf-frontend:latest

[package]
name = "container-per-ip"
version = "0.1.2"
authors = ["Ben Simms <ben@bensimms.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "container-per-ip"
path = "src/main.rs"

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
structopt = "0.3.17"
snafu = "0.6.8"
log = "0.4.11"
futures = "0.3.5"
lazy_static = "1.4.0"
multi-map = "1.3.0"
flexi_logger = "0.15.12"
ctrlc = "3.1.7"
pin-utils = "0.1.0"
bollard = "0.8.0"

[package.metadata.wharf.builder]
image = "clux/muslrust:latest"
target = "x86_64-unknown-linux-musl"

[package.metadata.wharf.output]
image = "docker:latest"
workdir = "/"
entrypoint = ["/bin/container-per-ip"]
stop-signal = "SIGINT"

[[package.metadata.wharf.binary]]
name = "container-per-ip"
destination = "/bin/container-per-ip"
