[package]
name = "container-per-ip"
version = "0.1.1"
authors = ["Ben Simms <ben@bensimms.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = { git = "https://github.com/nitros12/bollard.git", branch = "update-to-tokio-0.2" }
tokio = { version = "0.2.5", features = ["macros", "time", "stream", "io-util"] }
structopt = "0.3.5"
snafu = "0.6.0"
log = "0.4.8"
futures = "0.3.1"
lazy_static = "1.4.0"
multi-map = "1.2.0"
flexi_logger = "0.14.5"
ctrlc = "3.1.3"
pin-utils = "0.1.0-alpha.4"
